stages:
  - scan
  - build
  - test

build_app:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

scan-code:
  stage: scan
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn compile sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true

test_app:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn test
